name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Godot
        run: |
          sudo apt-get install snapd
          sudo snap install godot-4
          snap list godot-4
          echo "$(/snap/bin/godot-4 --version)"

      - name: Run Specs
        run: /snap/bin/godot-4 --headless -s spec/gspec_test.gd
