name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Godot
        run: |
          sudo apt-get install snapd
          sudo snap install godot-4

      - name: Run Specs
        run: |
          /snap/bin/godot-4 --headless -s spec/gspec_test.gd
          EXIT_CODE=$?
          echo $EXIT_CODE
          if [ $EXIT_CODE -ne 0 ]; then
            echo "this failed..."
            exit $EXIT_CODE
          fi
