name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Godot
        run: |
          brew install godot -y

      - name: Run Specs
        run: |
          godot --headless -s spec/gspec_test.gd
          EXIT_CODE=$?
          echo $EXIT_CODE
          if [ $EXIT_CODE -ne 0 ]; then
            echo "this failed..."
            exit $EXIT_CODE
          fi
